### ISSUE TITLE
Add documentation?

### ISSUE THREAD

**Issue by arm32x** [oysteinmyrmo/bezier#1]
It doesn't seem like there is any documentation for this library. I guess I'll just try to figure it out, but it would be great if you could add some documentation.

**Comment by oysteinmyrmo** [comment]
I haven't had the time to work on this library lately, but I will try to add some simple documentation for what is currently in there. In the meantime the best place to look is in the tests at https://github.com/oysteinmyrmo/bezier/tree/master/tests

**Comment by arm32x** [comment]
Thanks! I would love to see some work on this in the future.

**Comment by oysteinmyrmo** [comment]
I have added some initial documentation (mainly just sample usage showcasing the various functionality). Let me know if there is anything else that you would like to see in there or if anything is unclear.

**Comment by weifeng-sc** [comment]
I created a cubic Bézier curve, how should I extract the points on the curve, I want to use it for path planning
