### ISSUE TITLE
workflow problem matcher

### ISSUE THREAD

**Issue by atsju** [oysteinmyrmo/bezier#13]
I see you have created a workflow file. This is very good :)
May I suggest you add a problem matcher. Then warnings will show in PRs like this https://github.com/githubdoe/DFTFringe/pull/60/files

For GCC this one works great https://github.com/ammaraskar/gcc-problem-matcher but you should probably have one per compiler

**Comment by oysteinmyrmo** [comment]
I just released version 0.2.0: https://github.com/oysteinmyrmo/bezier/releases/tag/v0.2.0

There are now workflows for MSVC, XCode (AppleClang) and Clang/GCC (Ubuntu). All of these enable warnings as errors at the highest warning level (not _all_ warnings, but most) through the `test-bezier` target. This should catch all warnings expected in a production environment.

I will close this now, but I will keep it in mind if I want to use the workflow matcher at a later stage. Thanks for posting!
